M48
; DRILL file {KiCad 7.0.2} date Fri Oct 13 15:39:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-13T15:39:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X83.82Y-49.53
X83.82Y-137.16
X182.88Y-72.798
X219.71Y-49.53
X219.71Y-137.16
T0
M30
